version: '3.8'
services:
  person-service:
    container_name: person-service
    build:
      context: ../Person
      dockerfile: ../Person/Dockerfile
    networks:
      - spring-net
    restart: "on-failure"
    depends_on:
      person-mysql:
        condition: service_started
    image: person-service:latest
    ports:
      - 8081:8081

  person-mysql:
    container_name: person-mysql
    image: mysql:latest
    ports:
      - 3306:3306
    networks:
      - spring-net
    environment:
      - MYSQL_ROOT_PASSWORD=00000000
      - MYSQL_DATABASE=person_db
    volumes:
      - persondata:/var/lib/mysql
      - persondata:/etc/mysql/conf.d

#  rabbit-MQ:
#    container_name: rabbit-mq
#    image: rabbitmq:3-management
#    ports:
#      - 15672:15672
#      - 5672:5672
#    networks:
#      - spring-net
#    restart: "no"
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=password

networks:
  spring-net:
    name: spring-net
    driver: bridge

volumes:
  persondata:
